export const USER_PROFILE = '[User Profile]';

export const UPDATE_USER_REQUEST = `${USER_PROFILE} UPDATE_USER_REQUEST`;
export const UPDATE_USER_SUCCESS = `${USER_PROFILE} UPDATE_USER_SUCCESS`;
export const UPDATE_USER_ERROR = `${USER_PROFILE} UPDATE_USER_ERROR`;
export const CHANGE_PASSWORD_REQUEST = `${USER_PROFILE} CHANGE_PASSWORD_REQUEST`;
export const CHANGE_PASSWORD_SUCCESS = `${USER_PROFILE} CHANGE_PASSWORD_SUCCESS`;
export const CHANGE_PASSWORD_ERROR = `${USER_PROFILE} CHANGE_PASSWORD_ERROR`;
